spring:
  profiles: peer1
server:
  port: 8020
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://peer1:8020/eureka,http://peer2:8021/eureka
---
spring:
  profiles: peer2
server:
  port: 8021
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://peer1:8020/eureka,http://peer2:8021/eureka