spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sir-mllmn/config
    bus:
      enabled: true
server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8020/eureka, http://peer2:8021/eureka

management:
  security:
    enabled: false