spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sir-mllmn/config
server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka